### PR TITLE
Use BTreeSet for sync::State to allow deriving Hash

### PR DESCRIPTION
**Pull request by jeffa5**

### CODE REVIEW

**Comment by orionz** [comment]
Help me understand what this fixes?

**Comment by jeffa5** [comment]
`HashSet` doesn't implement `Hash` which means we can't store it in some scenarios (I'm particularly trying out some model checking), `BTreeSet` does implement `Hash` so we can use it as a substitute.

**Comment by jeffa5** [comment]
Maybe I should just create a new branch for my stuff since it might be making different tradeoffs from the core logic (though I want to keep it very close).

**Comment by orionz** [comment]
No this is fine.  I just wanted to know.  As long as we're not making the code overly complex or slow its all good.

**Pull request merged**
