### PR TITLE
Fix Clippy issues, broken tests, formatting issues

### PR DESCRIPTION
**Pull request by orionz**
A bunch of cleanup.  There are still two issues.  On the frontend there are some errors around `arbitrary::Arbitrary` not playing nicely with `smol_str::SmolStr`.  Also two tests are breaking in the wasm/js interop related to sync.  Anyone know where this came from?

### CODE REVIEW

**Comment by jeffa5** [comment]
I've added an `Arbitrary` implementation to `smol_str` and updated the version here https://github.com/automerge/automerge-rs/pull/190.

I'm not too sure on the sync issues, may be able to take a look sometime this week.

**Comment by jeffa5** [comment]
I think [this](https://github.com/automerge/automerge-rs/pull/193) fixes one of the sync test failures too

**Comment by jeffa5** [comment]
I think I've fixed the last js test too.

**Comment by jeffa5** [comment]
@alexjg Not sure what happened to CI again but I think this passes things locally.

**Review by alexjg — APPROVED** [review]

**Comment by jeffa5** [comment]
Running the tests I've found https://github.com/automerge/automerge-rs/issues/196 but I think that will be a separate PR so I'll merge this.

**Pull request merged**
