### PR TITLE
Remove default from ActorId

### PR DESCRIPTION
**Pull request by jeffa5**

### CODE REVIEW

**Comment by alexjg** [comment]
I find this a little worrying, mainly with regard to this sentence in the docs for `Default`:

> Default values are often some kind of initial value, identity value, or anything else that may make sense as a default.

This implies (to me) that `default()` should satisfy `default() == default()`, which `random()` does not. 

However, I'm aware that this is more of an objection to the fuzziness of the definition of `Default` than to this implementation (I'm sure there are people who do not have the intuition that `default() == default()`), is there some ergonomic reason to add this?

**Comment by jeffa5** [comment]
I can see why it would make sense to have `default() == default()` in most cases but I just noticed this as quite a footgun for users. Most users may not be wanting to use anything other than the standard ActorId  (uuids at the moment) so would reach for `ActorId::default()`, rather than giving them a sane default this gives them an empty actor id which will cause problems when sharing documents and with reuse of actor ids.

**Comment by alexjg** [comment]
My argument would be that we can't implement `Default` for `ActorId` at all. I agree that we definitely shouldn't have some kind of "empty" `ActorId` or anything for the reasons you give.

As I said though, this is more of a personal opinion than anything else, are there good reasons we might want a `Default` implementation (rather than just using `ActorId::random` directly)?

**Comment by jeffa5** [comment]
The empty value was just needed for the `mem::take` in the `diffable_sequence` so I've removed the `Default` implementation on `ActorId` and `OpId` and just implemented `Default` for `MultiValue` and `MultiGrapheme` directly (needed as the diffable sequence is generic over them so we can't use a `mem::replace`)

**Comment by alexjg** [comment]
This is better, it still upsets me to have a `Default` implementation for `MultiValue` as it's a way incorrect values could sneak in. Could we instead have a constant `UNSAFE_DUMMY: MultiValue` and then do `mem::replace(&target, UNSAFE_DUMMY.clone())` or similar?

**Comment by alexjg** [comment]
Or, it might make more sense to use an `Option<MultiValue>` and some `unwrap`s where we expect it not to be `None`, that way at least the logic error is obvious.

**Comment by jeffa5** [comment]
As the value is generic I've added a `take` function to the `DiffableValue` trait, this avoids having the default implementation while still keeping it quite simple.

**Comment by alexjg** [comment]
Nice, thanks for indulging me 🙂

**Review by alexjg — APPROVED** [review]

**Comment by jeffa5** [comment]
Just missed the `mem::replace` but that should work now.

**Review by alexjg — APPROVED** [review]

**Pull request merged**
