### PR TITLE
package for node and bundler

### PR DESCRIPTION
**Pull request by nornagon**
Based on investigations detailed in #33.

With this PR, and the package published to npm under `automerge-backend-wasm`,
the following would work:

```js
import wasmBackend from 'automerge-backend-wasm'
import Automerge from 'automerge'

wasmBackend.initCodecFunctions(Automerge)
Automerge.setDefaultBackend(wasmBackend)

// ... use Automerge, but it's fast now
```

I think we can follow up to remove the need to call `initCodecFunctions`, but
this works for now!

### CODE REVIEW

**Comment by nornagon** [comment]
hm, actually it looks like this doesn't work with webpack as-is, due to the async nature of webassembly loading. more investigation required!

**Comment by nornagon** [comment]
I got this to work with the old-style synchronous webpack wasm support, but the new-style async module version has issues with recursive imports.

sync version: https://gist.github.com/nornagon/5d0ba28f9509a85604628e70406f3f3c

with `--experiments-async-web-assembly`, an exception is thrown:

```
test_mjs.js:156 Uncaught (in promise) ReferenceError: Cannot access '__wbindgen_json_parse' before initialization
    at Module.__wbindgen_json_parse (test_mjs.js:156)
    at test_mjs.js:673
    at :5000/async http:/localhost:5000/test_mjs.js:187
    at :5000/async http:/localhost:5000/test_mjs.js:105
    at :5000/async http:/localhost:5000/test_mjs.js:22
    at :5000/async http:/localhost:5000/test_mjs.js:829
```

it looks like this is due to the recursive dependency between `index_bg.js` and `index_bg.wasm` generated by wasm-pack:

index_bg.js:
```js
import * as wasm from './index_bg.wasm';
// ...
```

index_bg.wasm (via wasm2wat):
```wat
// ...
  (import "./index_bg.js" "__wbindgen_json_parse" (func (;0;) (type 1)))
// ...
```

I think this might be a webpack bug. async modules and the experimental async webassembly support are both still very new (less than a month old) so it wouldn't be too surprising if that were the case.

**Comment by nornagon** [comment]
Hm, the async version seems to work properly if i `yarn pack`, untar the file and then `import wasmBackend from './package/index-bundler.js'`. So perhaps the webpack issue is a problem with `yarn link` and wouldn't be an issue if these packages were properly published to npm.

**Comment by echarles** [comment]
> Hm, the async version seems to work properly if i yarn pack and untar the module into node_modules (vs. yarn link). So perhaps the webpack issue is a problem with yarn link and wouldn't be an issue if these packages were properly published to npm.

I did not have good experience with yarn link, and moved in general to lerna. 

With this PR, will consumers need to expcitely import `automerge-backend-wasm/index-node.js` for node applications and  `automerge-backend-wasm/index-bundler.js` for e.g. webpack applications?

**Comment by orionz** [comment]
Hey guys - I did a bunch of experiments with different packaging but hit a dead end.  One, Im inexperienced with webpack - most of my experience with javascript is node/commonjs only.  Second I have some concerns about how people would want to consume a package like this - I posted my notes in a readme here - https://github.com/orionz/automerge-wasm-testapp

**Comment by echarles** [comment]
For sync wasm in webpack, I have used

```
module.exports = {
  experiments: {
      syncWebAssembly: true,
  }
};
```

I now read on https://webpack.js.org/configuration/experiments/#experiments

syncWebAssembly: Support the old WebAssembly like in webpack 4
asyncWebAssembly: Support the new WebAssembly according to the updated specification, it makes a WebAssembly module an async module

**Comment by tylersamples** [comment]
Maybe a naive question, but in the solutions presented it seems like there is a focus on working against the default behavior of browsers (i.e. trying to get the import to be sync or at the very least seem sync,) is there a reason why the `Automerge.setDefaultBackend` shouldn't be responsible for resolving the import (if it's necessary) instead of trying to introduce multi-layered packaging or shims?  If it has to be sync, has anyone explored proxies?

**Comment by matrushka** [comment]
I might be dropping in without being accurate about my comments but recently tried to run this with [Vite](https://vitejs.dev/), it was only possible with lots of modifications and would like to share some ideas.

I previously I tried [sql.js](https://sql.js.org/#/?id=usage) and running it with wasm was a breeze. Maybe something like that can work here as well to make the whole experience easier.

I tried using `web` target for for [wasm-pack](https://rustwasm.github.io/docs/wasm-bindgen/reference/deployment.html#without-a-bundler) and was able to get to a working solution (although I had to manually change some overlapping function names in the generated JS file). In my case my code looked like:

```js
import generateBackend from "automerge-backend-wasm/web";

const run = async () => {
  const backend = await generateBackend("/node_modules/automerge-backend-wasm/web/index_bg.wasm");
  Automerge.setDefaultBackend(backend);
  const doc = Automerge.from({});
  const newDoc = Automerge.change(doc, (docToChange: any) => {
    docToChange.list = [];
  })
};

run();
```

Although it's working now (at least creting an empty document), I somehow ended up with an `Automerge error: Decode failed` when a change triggers `applyLocalChange` method of the backend called (so I can't make any changes to a document). Not really sure it this is due to the way I made it work though.

Based on this little journey, adding an additional web target to the package looks like a lot easier way than finding & documenting the right configs for different bundlers or bundler versions over time (at least until bundlers align on the implementation of the standard).

**Pull request closed without merging**
