### PR TITLE
Add range functions to C API

### PR DESCRIPTION
**Pull request by jkankiewicz**
@orionz, I've exposed ten missing methods to the C API through the following six functions:
* `AMfork()`
* `AMlistGet()`
* `AMlistRange()`
* `AMmapGet()`
* `AMmapRange()`
* `AMobjValues()`

@lightsprint09, I've made the following backwards-incompatible changes to the C API:
* Added a `heads` argument to `AMlistGet()`.
* Added a `heads` argument to `AMmapGet()`.
* Renamed `AMdup()` to `AMclone()`.
* Renamed `AMgetActor()` to `AMgetActorId()`.
* Renamed `AMsetActor()` to `AMsetActorId()`.
* Renamed the `AMstrings` struct to `AMstrs`.

### CODE REVIEW

**Comment by alexjg** [comment]
@jkankiewicz the commits here seem quite small. Would it be possible to condenses them into a smaller set of commits with a high level description on each one of what's achieved?

**Comment by jkankiewicz** [comment]
> Would it be possible to condenses them into a smaller set of commits with a high level description on each one of what's achieved?

@alexjg, is there an upper limit on the number of commits per PR?

**Comment by alexjg** [comment]
It's more that the commit messages don't tell a good story about what's going on here. Quite a lot of the commits have very similar messages (e.g. there are more than four commits where the commit message contains "Added AMListItem") and don't describe why the change is necessary. It seems to me that those commits would be easier to write messages for if they were combined, with the commit message describing at a slightly higher level what's going on and why. Maybe it's just a case of writing different commit messages though rather than condensing the commits?

I know we haven't worried about commit messages much to date. I'm starting to think about them because this project is picking up contributors and users. I think that having a good commit trail makes it easy to review code but more importantly it makes it easier to understand why code is the way it is two years later when everyone has forgotten. I know people have different opinions about commit messages though and maybe it would be better to discuss that somewhere else, perhaps #405 ?

**Comment by jkankiewicz** [comment]
@alexjg, I'll try to redo the commits for this PR with higher-level descriptions in their messages.

**Comment by lightsprint09** [comment]
Is this ready to merge?

**Comment by jkankiewicz** [comment]
> Is this ready to merge?

@lightsprint09, it's good to hear from you!

This PR won't be merged until @orionz has approved it so you may wish to ask him for an estimate regarding if and when that will happen.

**Pull request merged**
