### PR TITLE
Add CMake support to resolve #264

### LINKED ISSUE #264: Support building automerge-c-v2 with Visual Studio
The 'C' bindings for the Automerge backend, automerge-c-v2, can't be built with Visual Studio for the Windows operating system because they only come with a makefile.

[CMake](https://cmake.org/) might be a good choice for enabling automerge-c-v2 to be built with Visual Studio for the following reasons:
* It can generate Visual Studio solution files.
* Recent versions of Visual Studio can read CMake files directly.
* It's the build system for Microsoft's [vcpkg](https://vcpkg.io/en/index.html) C/C++ dependency management system for open-source projects.
* It can generate makefiles for building on *nix distributions, too.

### PR DESCRIPTION
**Pull request by jkankiewicz**
I've added support for building the contents of the automerge-c-v2 directory with CMake in addition to GNU Make in order to resolve issue #264.

With these changes I'm able to build static and shared libraries from the automerge-c-v2 sources on both Windows 10 and Ubuntu Linux 21.04 (Hirsute Hippo).

When building with CMake, the test suite in automerge.c is also built and run for validation by default.

### CODE REVIEW

**Comment by alexjg** [comment]
This looks great, thanks for putting it together. Is there any way to test this stuff in CI?

Unfortunately I don't know much about cmake. I won't be able to maintain this and we have quite a few significant changes coming up (currently on the `experiment` branch). I think there's two ways forward, either a) @jkankiewicz are you able to commit to maintaining these build scripts for this project? or b) @orionz or @jeffa5 are either of you familiar enough with cmake and happy to maintain this?

**Comment by jeffa5** [comment]
I've not touched cmake before

**Comment by jkankiewicz** [comment]
> This looks great, thanks for putting it together.

You're welcome! I hope that being able to build the Rust backend's C bindings on Windows will enable more developers to use Automerge in their projects.

> Is there any way to test this stuff in CI?

Absolutely, a lot of open-source projects that integrate CI into their SCM workflows are built with CMake. 
How would someone go about including a PR into one of your project's CI builds so that I could demonstrate it?

> @jkankiewicz are you able to commit to maintaining these build scripts for this project?

I'm willing to do that if @orionz or @jeffa5 choose not to.

**Comment by orionz** [comment]
I too have zero experience with cmake.  But I'm very happy to see this.  @jkankiewicz , are you a C programmer by trade?  The C API is about to go through a major rewrite in the 'experimental' branch and I'm the closest thing we have to a C programmer here (and I haven't done C programming in anger for quite a while).  I don't know your level of interest or commitment around this but would you be interested in helping us with the C api rewrite?   The experimental branch is running 100x faster than the old API and exports an interface much more suitable for C (which was one of the primary goals of the whole endeavor).

**Comment by orionz** [comment]
CMake 3.18 eh?  Guess I finally need to upgrade to a current distro ;)

**Comment by jkankiewicz** [comment]
> CMake 3.18 eh?

@orionz, CMake == 3.18 is the oldest version I tested my changes with because it ships with Ubuntu 21.04; I tested with CMake == 3.22 on Windows 10.

> Guess I finally need to upgrade to a current distro ;)

Not necessarily, my changes *may* also work with some versions between 3.0 <= CMake < 3.18 but I'm unable to confirm which ones using my own equipment.

If you're able build automerge-c-v2 with an older version of CMake then the `cmake_minimum_required` lines should be updated to match its version.

**Comment by jkankiewicz** [comment]
> @jkankiewicz , are you a C programmer by trade?

@orionz, I'm a C++ and Python programmer by trade but I graduated from C and touch it every time I write Python bindings for a C++ library.

> [W]ould you be interested in helping us with the C api rewrite?

Yes, I would be.
I've already written a C++ library that wraps automerge-c-v2 and it would be nice if the rewritten C API could serve as the basis for an elegant C++ API. 

> The experimental branch is running 100x faster than the old API and exports an interface much more suitable for C (which was one of the primary goals of the whole endeavor).

That's fantastic!

**Comment by orionz** [comment]
It didn't work with cmake v 3.10 (ubuntu 18 LTS) so I upgraded to cmake v 3.18.4 (ubuntu 21.10) and still can't get it to build.  Not being familiar with cmake I'm not sure the source of the error.  Here are the relevant bits 

```
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:95 (add_library):
  add_library called with IMPORTED argument but no library type.


CMake Error at CMakeLists.txt:97 (target_sources):
  Cannot specify sources for target "INTERFACE" which is not built by this
  project.


CMake Error at CMakeLists.txt:117 (target_compile_definitions):
  Cannot specify compile definitions for target "INTERFACE" which is not
  built by this project.


CMake Error at CMakeLists.txt:119 (target_include_directories):
  Cannot specify include directories for target "INTERFACE" which is not
  built by this project.


-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
CMake Error at CMakeLists.txt:139 (target_link_libraries):
  Cannot specify link libraries for target "INTERFACE" which is not built by
  this project.


-- Configuring incomplete, errors occurred!
```

**Comment by jkankiewicz** [comment]
> It didn't work with cmake v 3.10 (ubuntu 18 LTS) so I upgraded to cmake v 3.18.4 (ubuntu 21.10) and still can't get it to build.

@orionz, did you invoke `cmake` from within the `automerge-rs/automerge-c-v2` directory or from within the `automerge-rs` directory?

Please try the following:
1. `cd <git-clone-parent-directory>/automerge-rs`
2. `cmake -B build`

CMake doesn't build anything directly but rather generates a build configuration for a platform-native build system. For *nixes, the build system defaults to GNU Make but others can be targeted depending upon which ones the platform provides.
I like to think of CMake as being the [wxWidgets](https://www.wxwidgets.org/) of build systems; it's a platform-neutral facade.

You should find the makefile it generated in the `<git-clone-parent-directory>/automerge-rs/build` directory. (If you don't specify the `-B <path-to-build>` command line option then it will write a makefile into the source tree instead but an out-of-source build is preferable.)
To build an SO instead, add the `-DBUILD_SHARED_LIBS=ON` command line option.
To add debugging symbols, add the `-DCMAKE_BUILD_TYPE=Debug` command line option.

Use GNU Make as you would normally to actually build the library e.g.
1. `cd build`
2. `make && make install`

**Comment by jkankiewicz** [comment]
@orionz, I've opened #266 for the subsequent `cargo build` error; it has nothing to do with CMake.

**Comment by jkankiewicz** [comment]
> ...we have quite a few significant changes coming up (currently on the experiment branch).

@alexjg, would it make more sense to add CMake support to the "experiment" branch instead?

**Comment by alexjg** [comment]
Yes definitely, that's where all our effort is going now. However, there currently isn't a C wrapper for that code so you would need to build one. Now, it sounds like you might be willing to do that (which is amazing!), if that's the case then yes, I would definitely suggest putting all this work into the `experiment` branch.

**Comment by jkankiewicz** [comment]
>  ...I would definitely suggest putting all this work into the experiment branch.

@alexjg, until #266 reared its ugly head, the "main" branch's C bindings have been stable enough that Cargo always built the library and so I could focus on only the CMake-related changes. How stable is the "experiment" branch and how soon do you anticipate its release?

**Comment by jkankiewicz** [comment]
@alexjg, are there any high-level descriptions of the backend, frontend and protocol APIs that you could provide me with?
I only know enough Rust to coerce CBindGen into outputting the C header into an arbitrary build directory so it would be nice to have some "why" to aid my interpretation of the "how".

**Comment by alexjg** [comment]
There aren't really any high level descriptions as yet. I'll try and put one together in the next few days. However, the underlying idea is that instead of having a backend/frontend split with the frontend exposing a recursive json-like data structure we have a simpler interface which operates on object IDs and properties.

Object IDs are the IDs of composite objects like maps or lists, properties are either indexes into a list, or keys of a map. Mutable operations then are things like `set`ting a property in an object to a value, or `inc`rementing a counter. I still need to write a bunch of documentation about this stuff but in the meantime here's a sort of succinct overview:

```rust
pub enum ObjType {
    Map,
    Table,
    List,
    Text,
}

pub enum Value {
    Object(ObjType),
    Scalar(ScalarValue),
}

pub enum ObjId;
pub struct ActorId(Vec<u8>);

pub enum ScalarValue {
    Bytes(Vec<u8>),
    Str(SmolStr),
    Int(i64),
    Uint(u64),
    F64(f64),
    Counter(Counter),
    Timestamp(i64),
    Boolean(bool),
    Null,
}

impl Automerge {
    // Creation logic
    pub fn new() -> Self;
    pub fn new_with_actor_id(actor: ActorId) -> Self;

    // Mutation functions 
    pub fn set<P: Into<Prop>, V: Into<Value>>(
        &mut self,
        obj: &ObjId,
        prop: P,
        value: V,
    ) -> Result<Option<ObjId>, AutomergeError>;

    pub fn insert<V: Into<Value>>(
        &mut self,
        obj: &ObjId,
        index: usize,
        value: V,
    ) -> Result<Option<ObjId>, AutomergeError>;

    pub fn inc<P: Into<Prop>>(
        &mut self,
        obj: &ObjId,
        prop: P,
        value: i64,
    ) -> Result<(), AutomergeError>;

    pub fn del<P: Into<Prop>>(&mut self, obj: &ObjId, prop: P) -> Result<(), AutomergeError>;

    pub fn splice(
        &mut self,
        obj: &ObjId,
        mut pos: usize,
        del: usize,
        vals: Vec<Value>,
    ) -> Result<Vec<ObjId>, AutomergeError>;

    //Transaction handling. A "transaction" is started implicitly whenever you mutate a document
    pub fn commit(&mut self, message: Option<String>, time: Option<i64>) -> Vec<ChangeHash>;

    pub fn rollback(&mut self) -> usize;

    // Read logic
    pub fn keys(&self, obj: &ObjId) -> Vec<String>;
    pub fn length(&self, obj: &ObjId) -> usize;
    pub fn text(&self, obj: &ObjId) -> Result<String, AutomergeError>;
    pub fn value<P: Into<Prop>>(
        &self,
        obj: &ObjId,
        prop: P,
    ) -> Result<Option<(Value, ObjId)>, AutomergeError>;
    pub fn values<P: Into<Prop>>(
        &self,
        obj: &ObjId,
        prop: P,
    ) -> Result<Vec<(Value, ObjId)>, AutomergeError>;


    // Read logic but scoped to a particular point in time, identified by the hashes of the heads
    // at that point
    pub fn keys_at(&self, obj: &ObjId, heads: &[ChangeHash]) -> Vec<String>;
    pub fn length_at(&self, obj: &ObjId, heads: &[ChangeHash]) -> usize;
    pub fn text_at(&self, obj: &ObjId, heads: &[ChangeHash]) -> Result<String, AutomergeError>;
    pub fn value_at<P: Into<Prop>>(
        &self,
        obj: &ObjId,
        prop: P,
        heads: &[ChangeHash],
    ) -> Result<Option<(Value, ObjId)>, AutomergeError>;
    pub fn values_at<P: Into<Prop>>(
        &self,
        obj: &ObjId,
        prop: P,
        heads: &[ChangeHash],
    ) -> Result<Vec<(Value, ObjId)>, AutomergeError>;

    // Saving and loading
    pub fn load(data: &[u8]) -> Result<Self, AutomergeError> {
        let changes = Change::load_document(data)?;
        let mut doc = Self::new();
        doc.apply_changes(&changes)?;
        Ok(doc)
    }

    pub fn load_incremental(&mut self, data: &[u8]) -> Result<usize, AutomergeError> {
        let changes = Change::load_document(data)?;
        let start = self.ops.len();
        self.apply_changes(&changes)?;
        let delta = self.ops.len() - start;
        Ok(delta)
    }

    /// Takes all the changes in `other` which are not in `self` and applies them
    pub fn merge(&mut self, other: &mut Self);

    pub fn save(&mut self) -> Result<Vec<u8>, AutomergeError>;

    // should this return an empty vec instead of None?
    pub fn save_incremental(&mut self) -> Vec<u8>;

    pub fn get_missing_deps(&mut self, heads: &[ChangeHash]) -> Vec<ChangeHash>;

}
```

**Comment by alexjg** [comment]
As regards stability. There's a lot in flux right now. We're working to get a release out ASAP but there's still likely to be quite a few API changes - nothing giant but things like error types and the mutability of various `self` parameters.

**Comment by jkankiewicz** [comment]
> I still need to write a bunch of documentation about this stuff but in the meantime here's a sort of succinct overview:

@alexjg, I see that a transaction is started implicitly via a mutating operation and finished explicitly via a `commit` or `rollback` call. Is there no need for an idempotent call that indicates if a transaction is still in progress or not?

Also, does the new API support undo/redo?

**Comment by alexjg** [comment]
> Is there no need for a non-mutating call that indicates if a transaction is still in progress or not?

Maybe. I think we're somewhat on the fence as to whether we should expose a transaction API _at all_ or whether it should be an internal implementation detail. we already auto-commit on demand anyway (e.g. when saving the document). I think undo/redo is probably the main reason it might make sense to expose this API. @orionz thoughts?

**Comment by jkankiewicz** [comment]
> There aren't really any high level descriptions as yet. I'll try and put one together in the next few days.

@alexjg, thanks in advance for doing that! It should definitely help with documentation.

**Comment by alexjg** [comment]
Quick sitrep here, I'm busy this weekend so I probably won't get this documentation done until mid next week.

**Comment by jkankiewicz** [comment]
> I'm busy this weekend so I probably won't get this documentation done until mid next week.

@alexjg, no problem; I understand.

BTW, is there a child branch of "experiment" in which the `types::Patch` type is implemented or will it be completely stricken from the `automerge::Automerge` type's public API?

**Comment by alexjg** [comment]
There isn't a child branch but I think we will need some kind of patch API. I would personally like to have something much more lightweight than the patch API in the current version of automerge which is very complicated to interact with. We still need to design this.

**Comment by orionz** [comment]
Hey sorry I got diverted - this looks good - can you just move the cmake stuff into  automerge-c-v2 folder and out of the root folder?  I'd like to keep the C stuff contained to its own subfolder.  

As for the experimental branch.  I know what I want the C api to look like (more or less) I just haven't had time to get started.  I'd be happy to have a zoom call with you and we can sketch how it should look/work.


> @alexjg, would it make more sense to add CMake support to the "experiment" branch instead?

It is my hope to EOL this branch as soon as I can.  The experimental branch is shaping up to be better in every way.

**Comment by jkankiewicz** [comment]
> Hey sorry I got diverted - this looks good - can you just move the cmake stuff into automerge-c-v2 folder and out of the root folder?

@orionz, yes, I can do that.

**Comment by jkankiewicz** [comment]
@orionz, all of the CMake stuff is in the automerge-c-v2 folder now.

To build and install the C bindings with CMake on a *nix distro, do the following:
1. `cd automerge-rs/automerge-c-v2`
2. `mkdir build`
3. `cd build`
4.
    * `cmake -S .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=OFF`
    * `cmake -S .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON`
    * `cmake -S .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF`
    * `cmake -S .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON`
5. `make`
6. `sudo make install`

There are multiple ways to build and install the C bindings on Windows; importing the automerge-rs/automerge-c-v2/CMakeLists.txt file directly into a Windows IDE that integrates with CMake is probably the easiest.

**Comment by jkankiewicz** [comment]
> I know what I want the C api to look like (more or less) I just haven't had time to get started. I'd be happy to have a zoom call with you and we can sketch how it should look/work.

@orionz, that sounds great. I can "meet" with you early in the morning this coming weekend.
I'll open a PR containing the work I've already done on it beforehand.

**Comment by orionz** [comment]
I've started work on a new C Api in a branch called "c_api".  I decided to follow the basic shape of the PostgreSQL C API and I feel it handles a bunch of the issues I was having with the old api better.

**Comment by jkankiewicz** [comment]
> I've started work on a new C Api in a branch called "c_api".

@orionz, it looks really good so far!

**Comment by orionz** [comment]
This is all being moved to the exp branch.

**Pull request closed without merging**
