### PR TITLE
Rename `del` and `inc` to `delete` and `increment`

### PR DESCRIPTION
**Pull request by jeffa5**
Rename `del` and `inc` to `delete` and `increment`.

I've also changed them in js/wasm but if that causes a conflict with js internals then we can revert the delete one.

### CODE REVIEW

**Comment by ept** [comment]
I like this. I think `delete` is a keyword in JS, but AFAIK all JS engines except for Internet Explorer 8 and older nevertheless allow `delete` as a function name. (This information is based on the fact that [Immutable.js has a function called `delete`](https://immutable-js.com/docs/v4.0.0/Map/#delete()), which is documented to be unavailable only in IE8.) Given that IE8 doesn't support Wasm either, I think we can safely use `delete`.

Since we're renaming operations, another one I've considered is whether we should rename `set` to `assign`, because the word "set" is ambiguous: as a verb it refers to updating something, whereas as a noun it refers to a collection ("the set of objects"). What do folks think of that?

**Comment by jeffa5** [comment]
Interesting, `delete` may be ok then.

I agree `set` could be ambiguous, I'll throw in `put` as another option which, in my mind at least, is commonly used for overwriting things if they exist.

**Comment by ept** [comment]
I'd be fine with `put` as well.

**Comment by alexjg** [comment]
I like this! I'm also fine with `put`.

**Review by alexjg — APPROVED** [review]

**Review by alexjg — APPROVED** [review]

**Pull request merged**
