### PR TITLE
Build experimental C API with CMake

### LINKED ISSUE #264: Support building automerge-c-v2 with Visual Studio
The 'C' bindings for the Automerge backend, automerge-c-v2, can't be built with Visual Studio for the Windows operating system because they only come with a makefile.

[CMake](https://cmake.org/) might be a good choice for enabling automerge-c-v2 to be built with Visual Studio for the following reasons:
* It can generate Visual Studio solution files.
* Recent versions of Visual Studio can read CMake files directly.
* It's the build system for Microsoft's [vcpkg](https://vcpkg.io/en/index.html) C/C++ dependency management system for open-source projects.
* It can generate makefiles for building on *nix distributions, too.

### PR DESCRIPTION
**Pull request by jkankiewicz**
I've added support for building the contents of the automerge-rs/automerge-c directory with [CMake](https://cmake.org/) in order to resolve #264 for @orionz's "c_api" branch.

I've also tweaked the automerge-rs/automerge-c/cbindgen.toml file in order to resolve the issue raised by [Duncan Wilcox](https://app.slack.com/team/U016Q92NHFW) in [his post](https://automerge.slack.com/archives/CTQARU3NZ/p1631431669003100) from September 12, 2021 on the #automerge-rs Slack channel.

To build and install the C bindings with CMake on a *nix distro, do the following:
1. `cd automerge-rs/automerge-c`
2. `mkdir build`
3. `cd build`
4.
    * `cmake -S .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=OFF`
    * `cmake -S .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON`
    * `cmake -S .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF`
    * `cmake -S .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON`
5. `make`
6. `sudo make install`

There are multiple ways to build and install the C bindings on Windows; importing the automerge-rs/automerge-c/CMakeLists.txt file directly into a Windows IDE that integrates with CMake is probably the easiest.

### CODE REVIEW

**Comment by orionz** [comment]
This looks great!  As I'm not familiar with CMake, could you add something to the README.md to clarify it use to people who need CMake.  If there's only one obvious way to use it and anyone coming in with CMake knowledge will understand then we can skip this and just merge it in.

**Comment by orionz** [comment]
There are still a LOT of functions that need to be written - PR's filling in any of those would be awesome.  Also any just basic feedback on how to deal with things like testing and "packaging" in an idiomatic C way would be welcome.

**Comment by jkankiewicz** [comment]
> As I'm not familiar with CMake, could you add something to the README.md to clarify it use to people who need CMake.

@orionz, you're right of course; the instructions for building with CMake should be in the README.

**Comment by jkankiewicz** [comment]
> Also any just basic feedback on how to deal with things like testing and "packaging" in an idiomatic C way would be welcome.

@orionz, I'm not aware of any idiomatic C ways of testing and packaging other than to just use the platform's native toolchain(s).

However, CMake does furnish cross-platform testing through [CTest](https://cmake.org/cmake/help/latest/module/CTest.html) and cross-platform packaging through [CPack](https://cmake.org/cmake/help/latest/module/CPack.html).

If by "testing" you instead mean a C framework for writing unit tests then there are several non-standard ones based on Java's JUnit framework (which is itself based on Smalltalk's SUnit framework). I could do some research on those.

**Comment by alexjg** [comment]
I think it would be worth adding a CI step to run this build if we can. The way to do that would be to add a script to `scripts/ci`, maybe call it something like `scripts/ci/cmake-build`, this would just be a simple script that invokes cmake. Then add it to the end of `./scripts/ci/run` (which is useful for running all the ci steps locally). Finally you would need to add a step to `.github/workflows/ci.yaml` to actually invoke the build.

**Review by alexjg — APPROVED** [review]
Looks great!

**Comment by jkankiewicz** [comment]
> Finally you would need to add a step to .github/workflows/ci.yaml to actually invoke the build.

@alexjg, that part isn't working yet so there's going to be at least one more push.

**Comment by orionz** [comment]
> > Also any just basic feedback on how to deal with things like testing and "packaging" in an idiomatic C way would be welcome.
> 
> @orionz, I'm not aware of any idiomatic C ways of testing and packaging other than to just use the platform's native toolchain(s).
> 
> However, CMake does furnish cross-platform testing through [CTest](https://cmake.org/cmake/help/latest/module/CTest.html) and cross-platform packaging through [CPack](https://cmake.org/cmake/help/latest/module/CPack.html).
> 
> If by "testing" you instead mean a C framework for writing unit tests then there are several non-standard ones based on Java's JUnit framework (which is itself based on Smalltalk's SUnit framework). I could do some research on those.

Before I had a single `automerge.c` that I could build and run that would exit 0 if all tests passed.  It was ok in that it detected when I broke things but mostly I want C people coming to this repo to not facepalm because I missed an obviously better to do things that I didn't know b/c I'm super out of the loop on how C projects are run these days. 😅  If there is real standard and everyone just rolls their own then that's ok too.

**Comment by jkankiewicz** [comment]
> [M]y last commit was premature because it doesn't actually contain any changes to `.github/workflows/ci.yaml`...

@alexjg, I think I've added everything you asked for now.

**Comment by jkankiewicz** [comment]
> I want C people coming to this repo to not facepalm because I missed an obviously better to do things that I didn't know b/c I'm super out of the loop on how C projects are run these days.

@orionz, I don't think there's much risk of that; there isn't even a standard unit testing library for C++.

IMHO, the main benefits of using a JUnit-based unit testing framework are:
* It's easier for other developers to add tests to your test suite(s).
* It can output test results in a common format like [JUnit XML](https://llg.cubic.org/docs/junit/), [Subunit](https://en.wikipedia.org/wiki/Subunit_(format)) or [TAP](https://testanything.org/).

**Review by alexjg — APPROVED** [review]

**Comment by alexjg** [comment]
> @alexjg, I think I've added everything you asked for now.

Thanks for this!

**Comment by jkankiewicz** [comment]
> There are still a LOT of functions that need to be written - PR's filling in any of those would be awesome.

@orionz, I will be submitting a PR containing the work I'd already done before you created the "c_api" branch. I just have to finish meshing it with your work.

**Comment by jkankiewicz** [comment]
> There are still a LOT of functions that need to be written - PR's filling in any of those would be awesome.

@orionz, I've started with PR #275 which fills in a missing function and adds an unbidden one.

**Comment by jkankiewicz** [comment]
> IMHO, the main benefits of using a JUnit-based unit testing framework are:

@orionz, I thought of another reason: a unit testing framework's assertions work the same for "Release" builds as they do for "Debug" builds whereas a C compiler elides `assert` macro expansions in a release build.

For example, a test case in a "Release" build of `automerge-rs/automerge-c/automerge.c` can only fail by crashing the executable.

**Pull request merged**
